<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecPerf.Domain\SecPerf.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Dtos\" />
    <Folder Include="Extensions\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Validators\" />
    <Folder Include="Queries\" />
  </ItemGroup>

</Project>
